export const DmsDocumentFormConstants = {
    defaultSectionsToFieldsMap: {
        "Main": [
            "Title",
            "ProjectReference",
            "ProjectRevision",
            "PLOwnership",
            "DocumentType",
            "DocumentLanguage",
            "ABS",
            "PBS",
            "SubmissionCategory",
            "PlannedSubmissionDate",
            "IssuingEntity",
            "ConfidentialityLevel",
            "GRMilestone",
            "Authors",
            "_Comments",
            "AlstomReference"
        ],
        "Additional Properties": [
            "WBS",
            "DBS",
            "FBS",
            "SBS",
            "SupplierReference",
            "SupplierRevision",
            "SupplierName",
            "OtherReference",
            "OtherRevision",
            "RequirementID",
            "ChangeRequestID",
            "Keywords",
            "FolioNumber",
            "AlstomPartNoReference",
            "AlstomPartNoRevision",
            "ExternalURL",

        ],
        "Project": [
            "Projectattr1",
            "Projectattr2",
            "Projectattr3",
            "Projectattr4",
            "Projectattr5",
            "Projectattr6",
            "Projectattr7",
            "Projectattr8",
            "Projectattr9",
            "Projectattr10"
        ],
        "Additional SER": [
            "LineNumber",
            "MoCStatus",
            "AssetID",
            "MaterialID",
            "LocationID",
            "JobPlanID",
            "InspectionID",
            "FailureID",
            "MaintenancePlanID",
            "HazardID",
            "PermitToWorkID",
            "MoCID",
            "IncidentID",
            "HandoverDocumentClassification",
            "HandoverDocumentTitle",
            "HandoverDocumentCode",
            "HandoverDocumentFilename",
            "HandoverPBSLevelCode",
            "HandoverDocumentStatus",
            "HandoverDocumentRevision"
        ],
        "Follow up": [
            "CustomerResponseExpectedDate",
            "CustomerResponseReference",
            "CustomerResponseDate",
            "CustomerResponseStatus",
            "ReforecastSubmissionDate",
            "ActualSubmissionDate",
            "CustomerMilestone",
            "TransmittalReference",
            "TransmittalDate",
            "ApprovalCycleLaunchDate",
            "Verifiedby",
            "VerificationDate",
            "Validatedby",
            "ValidationDate",
            "Approvedby",
            "ApprovalDate",
            "CustomerComments",
        ],
        "Applicability": [
            "EffectiveDate",
            "ExpiryDate",
            "ReplacementFor",
            "ReplacedBy",
            "ChangeFromNumber",
            "ChangeToNumber",
            "SafetyCriticity",
        ],
        "Technical Properties": [
            "Author",
            "Created",
            "Editor",
            "Modified"
        ]
    },
    hideInEditForm: [
        "_dlc_DocId",
        "_dlc_DocIdUrl",
        "_ExtendedDescription",
        "DocumentStatus",
        "WorkflowStatus",
        "DocumentSetDescription"
    ],
    hideInNewForm: [
        "_ExtendedDescription",
        "WorkflowStatus",
        "DocumentSetDescription",
        "DocumentStatus", "ActualSubmissionDate", "TransmittalReference", "TransmittalDate", "ApprovalCycleLaunchDate", "Verifiedby",
        "VerificationDate", "Validatedby", "ValidationDate", "Approvedby", "ApprovalDate", "AlstomReference", "DocumentStatus",
        "WorkflowStatus", "ScopeCountry", "CustomernameDirect", "CustomernameFinal", "ProductName", "ProjectAlias1",
        "_dlc_DocId", "_dlc_DocIdUrl", "_ExtendedDescription", "Author", "Created", "Editor", "Modified"
    ],
    hideInViewForm: [],
    disableInEditForm: [
        "ProjectReference", "ProjectRevision", "PLOwnership", "CustomerResponseExpectedDate", "CustomerResponseDate",
        "ActualSubmissionDate", "TransmittalReference", "TransmittalDate", "ApprovalCycleLaunchDate", "Verifiedby",
        "VerificationDate", "Validatedby", "ValidationDate", "Approvedby", "ApprovalDate", "AlstomReference", "DocumentStatus",
        "WorkflowStatus", "ScopeCountry", "CustomernameDirect", "CustomernameFinal", "ProductName", "ProjectAlias1",
        "_dlc_DocId", "_dlc_DocIdUrl", "_ExtendedDescription", "Author", "Created", "Editor", "Modified"
    ],
    disableInNewForm: [],

    enableInApplicableViewForm: ["Contractual", "CustomerRevision", "CustomerMilestone", "PlannedSubmissionDate",
        "ReforecastSubmissionDate", "ActualSubmissionDate",
        "TransmittalReference", "CustomerResponseExpectedDate", "CustomerResponseReference",
        "CustomerResponseDate", "CustomerResponseStatus",
        "CustomerComments"
    ],
    enableInApplicableViewFormDateFields: ["PlannedSubmissionDate",
        "ReforecastSubmissionDate", "ActualSubmissionDate",
        "CustomerResponseExpectedDate",
        "CustomerResponseDate"
    ],
    enableInApplicableViewFormBooleanFields: ['Contractual'],

    dmsUserApiAppId: "api://5558567f-a32f-417c-a15c-3e57b67f887e",
    confidentialityEndpoint: "https://lab-dms-int-fnapp-user-api.azurewebsites.net/api/confidentiality?code=7UdNGawE1jtHAJ_nH506T94FPHtCk9jWjpZIaEsBVnl5AzFuuMJOBw%3D%3D",
    updateApplicableDocumentEndpoint: "https://lab-dms-int-fnapp-user-api.azurewebsites.net/api/applicableDocument?code=g9KiiJXZFE9gcdGui_5Y6reGDlLxqiJ-nkvy0yjFFwMJAzFujkcXmA%3D%3D"

};